### ISSUE TITLE
Mantis Produces "inf"

### ISSUE THREAD

**Issue by zsxing99** [giorgk/Mantis#17]
Multiple runs produce "inf" data point, how should we interpret this? Is it just a bug?

One of the input:
```
endSimYear 2100 startRed 2021 endRed 2032 flowScen C2VsimRun01Ref6 loadScen SWAT1 unsatScen C2VSIM_SPRING_2000 unsatWC 0.0000 bMap CentralValley Nregions 1 CentralValley Ncrops 49 2 1.0000 3 1.0000 4 1.0000 5 1.0000 6 1.0000 7 1.0000 8 1.0000 9 1.0000 11 1.0000 13 1.0000 14 1.0000 15 1.0000 17 1.0000 20 1.0000 22 1.0000 24 1.0000 26 1.0000 27 1.0000 30 1.0000 29 1.0000 31 1.0000 34 1.0000 36 1.0000 37 1.0000 38 1.0000 39 1.0000 40 1.0000 41 1.0000 42 1.0000 46 1.0000 47 1.0000 48 1.0000 49 1.0000 50 1.0000 51 1.0000 52 1.0000 53 1.0000 55 1.0000 56 1.0000 57 1.0000 1 1.0000 10 1.0000 12 1.0000 32 1.0000 33 1.0000 35 1.0000 43 1.0000 44 1.0000 45 1.0000 ENDofMSG\n
```

I have attached one of the output files.
https://github.com/zsxing99/Mantis/blob/error-report3/data/error/test.txt

**Comment by giorgk** [comment]
There was a bug in SWAT, which seems to cause those `inf` values
I have fixed that in the latest commit and I don't get any 'inf` in the results of the above input.
Make sure that you get the latest C2VsimRun01Ref6_urfs.mnts file.
I'm attaching a figure with the percentiles. 

![image](https://user-images.githubusercontent.com/2207656/117453714-1e662600-aefa-11eb-97a2-0ac144e59746.png)

**Comment by zsxing99** [comment]
The issue persists in all inputs with `SWAT` scenario, even in the lastest commit.

I can provide several inputs:
```
endSimYear 2500 startRed 2020 endRed 2020 flowScen C2VsimRun01Ref6 loadScen SWAT1 unsatScen C2VSIM_SPRING_2015 unsatWC 0.0000 bMap B118 Nregions 3 5_22_06 5_22_02 5_22_16 Ncrops 1 -9 1.0000 ENDofMSG
```

```
endSimYear 2100 startRed 2020 endRed 2025 flowScen C2VsimRun01Ref6 loadScen SWAT2 unsatScen C2VSIM_SPRING_2015 unsatWC 0.0000 bMap B118 Nregions 3 5_22_02 5_22_16 5_21_67 Ncrops 1 -9 1.0000 ENDofMSG
```

```
endSimYear 2100 startRed 2024 endRed 2032 flowScen C2VsimRun01Ref6 loadScen SWAT4 unsatScen C2VSIM_SPRING_2015 unsatWC 0.0000 bMap Counties Nregions 2 Tuolumne Merced Ncrops 3 -9 0.6200 46 1.0000 10 1.0000 ENDofMSG
```

**Comment by giorgk** [comment]
I rerun all examples and I didn't get any inf values. Can you run one of them passing the `DebugID` option. 
To use `DebugID` you have to run with 1 thread, otherwise all threads will write onto the same files. 
Then can you upload somewhere the 4 files ***urf.dat**, ***lf.dat**, ***btc.dat** and ***well_btc.dat**?

**Comment by zsxing99** [comment]
Oh sorry! There is no more `inf`.

I updated the project and ran `cmake`, but I forgot to `make`. 🤯

It is resolved now.
